environment: staging
container:
  name: node-service
  port: 3000
  image: greenlemon/node-service
  tag: latest
  resources:
    requests:  
      memory: "10Mi"
      cpu: "100m"
    limits:
      memory: "20Mi"
      cpu: "250m"
replicas: 1
